version: '3.8'

services:
  app:
    build: ./app
    container_name: node_app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
